GET  http://127.0.0.1:8080/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTUyODM1MDA2ODE0MjQ4NjdjZmQxNDUiLCJ1c2VyTmFtZSI6IlRvbSIsImVtYWlsIjoidG9tLndhbmczQHV3YXRlcmxvby5jYSIsImlhdCI6MTcwMDI5MTExMywiZXhwIjoxNzAxMTU1MTEzfQ.TEsNNGVDFHmK-BdbS6CdzJ_0cWvDlvDqobiInsX22xw

### Sign up

POST http://127.0.0.1:8080/user/register
Content-Type: application/json

{
    "userName": "Jerry",
    "phone": "1234590",
    "email": "jerry@test.test",
    "password": "1234"
}

### Log in

POST http://127.0.0.1:8080/user/login
Content-Type: application/json

{
    "userName": "Tom",
    "password": "1234"
}